from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Room, Furniture
import json

def hello(request):
    return JsonResponse({'message': 'Hello world!'})

def foobar(request):
    return JsonResponse({'message': "Foobar endpoint"})

@csrf_exempt
def rooms_list(request):
    """
    GET = return list of rooms
    POST = create new room
    """
    if request.method == "GET":
        rooms = Room.objects.all()
        data = [
            {
                "id": room.id,
                "name": room.name
            }
            for room in rooms
        ]
        return JsonResponse(data, safe=False)

    if request.method == "POST":
        body = json.loads(request.body)
        room = Room.objects.create(name=body["name"])
        return JsonResponse({"id": room.id, "name": room.name}, status=201)
        
@csrf_exempt
def room_detail(request, room_id):
    """
    PUT = update
    DELETE = delete
    """
    try:
        room = Room.objects.get(id=room_id)
    except Room.DoesNotExist:
        return JsonResponse({"error": "Room not found"}, status=404)

    if request.method == "PUT":
        body = json.loads(request.body)
        room.name = body.get("name", room.name)
        room.save()
        return JsonResponse({"id": room.id, "name": room.name})

    if request.method == "DELETE":
        room.delete()
        return JsonResponse({"status": "deleted"})

@csrf_exempt
def room_furniture(request, room_id):
    """
    GET = return list of furniture from room
    """
    try:
        room = Room.objects.get(id=room_id)
    except Room.DoesNotExist:
        return JsonResponse({"error": "Room not found"}, status=404)

    furniture = room.furniture.all()
    data = []
    for f in furniture:
        data.append({
            "id": f.id, # primary key (auto-generated by Django)
            "iconUrl": None,
            "name": f.name
        })

    return JsonResponse(data, safe=False)

@csrf_exempt
def furniture_list(request):
    """
    GET = return list of furniture
    POST = create new furniture
    """
    if request.method == "GET":
        furniture = Furniture.objects.all()
        data = []
        for f in furniture:
            data.append({
                "id": f.id, # primary key (auto-generated by Django)
                "roomId": f.room.id,
                "name": f.name,
                "description": f.description,
                "question": f.questions
            })
        return JsonResponse(data, safe=False)

    if request.method == "POST":
        body = json.loads(request.body)
        try:
            room = Room.objects.get(id=body["roomId"])
        except Room.DoesNotExist:
            return JsonResponse({"error": "Room not found"}, status=404)

        furniture = Furniture.objects.create(
            room = room,
            name = body["name"],
            description = body.get("description", ""),
            questions = body.get("question", []),
        )
        return JsonResponse({
            "id": furniture.id,
            "roomId": furniture.room.id,
            "name": furniture.name,
            "description": furniture.description,
            "question": furniture.questions,
        }, status=201)

@csrf_exempt
def furniture_detail(request, furniture_id):
    """
    GET = fetch one furniture
    PUT = update
    DELETE = delete
    """
    try:
        furniture = Furniture.objects.get(id=furniture_id)
    except Furniture.DoesNotExist:
        return JsonResponse({"error": "Furniture not found"}, status=404)

    if request.method == "GET":
        return JsonResponse({
            "id": furniture.id,
            "roomId": furniture.room.id,
            "name": furniture.name,
            "description": furniture.description,
            "question": furniture.questions
        })

    if request.method == "PUT":
        body = json.loads(request.body)
        furniture.name = body.get("name", furniture.name)
        furniture.description = body.get("description", furniture.description)
        furniture.question = body.get("question", furniture.questions)

        if "roomId" in body:
            try:
                room = Room.objects.get(id=body["roomId"])
                furniture.room = room
            except Room.DoesNotExist:
                return JsonResponse({"error": "Room not found"}, status=404)

        furniture.save()
        return JsonResponse({
            "id": furniture.id,
            "roomId": furniture.room.id,
            "name": furniture.name,
            "description": furniture.description,
            "question": furniture.questions
        })

    if request.method == "DELETE":
        furniture.delete()
        return JsonResponse({"status": "deleted"})
