from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from .models import Room, Furniture, Flashcard
import json
from django.utils import timezone
from .services.spaced_repetition import apply_sm2

def hello(request):
    return JsonResponse({'message': 'Hello world!'})

def foobar(request):
    return JsonResponse({'message': "Foobar endpoint"})

@csrf_exempt
def rooms_list(request):
    """
    GET = return list of rooms
    POST = create new room
    """
    if request.method == "GET":
        rooms = Room.objects.all()
        data = [
            {
                "id": room.id,
                "name": room.name
            }
            for room in rooms
        ]
        return JsonResponse(data, safe=False)

    if request.method == "POST":
        body = json.loads(request.body)
        room = Room.objects.create(name=body["name"])
        return JsonResponse({"id": room.id, "name": room.name}, status=201)
        
@csrf_exempt
def room_detail(request, room_id):
    """
    PUT = update
    DELETE = delete
    """
    try:
        room = Room.objects.get(id=room_id)
    except Room.DoesNotExist:
        return JsonResponse({"error": "Room not found"}, status=404)

    if request.method == "PUT":
        body = json.loads(request.body)
        room.name = body.get("name", room.name)
        room.save()
        return JsonResponse({"id": room.id, "name": room.name})

    if request.method == "DELETE":
        room.delete()
        return JsonResponse({"status": "deleted"})

@csrf_exempt
def room_furniture(request, room_id):
    """
    GET = return list of furniture from room
    """
    try:
        room = Room.objects.get(id=room_id)
    except Room.DoesNotExist:
        return JsonResponse({"error": "Room not found"}, status=404)

    furniture = room.furniture.all()
    data = []
    for f in furniture:
        data.append({
            "id": f.id, # primary key (auto-generated by Django)
            "iconUrl": None,
            "name": f.name
        })

    return JsonResponse(data, safe=False)

@csrf_exempt
def furniture_list(request):
    """
    GET = return list of furniture
    POST = create new furniture
    """
    if request.method == "GET":
        furniture_qs = Furniture.objects.all()
        data = []

        for f in furniture_qs:
            data.append({
                "id": f.id,
                "roomId": f.room.id,
                "name": f.name,
                "description": f.description,
                "flashcards": [
                    {
                        "id": fc.id,
                        "front": fc.front,
                        "back": fc.back,
                        "interval": fc.interval,
                        "ease_factor": fc.ease_factor,
                        "repetition": fc.repetition,
                        "next_review": fc.next_review.isoformat()
                    }
                    for fc in f.flashcards.all()  # <--- używamy .all()
                ],
            })
        return JsonResponse(data, safe=False)

    if request.method == "POST":
        body = json.loads(request.body)
        try:
            room = Room.objects.get(id=body["roomId"])
        except Room.DoesNotExist:
            return JsonResponse({"error": "Room not found"}, status=404)

        user = User.objects.first()
        furniture = Furniture.objects.create(
            room=room,
            name=body["name"],
            description=body.get("description", ""),
            user=user
        )

        flashcards_data = body.get("flashcards", [])
        for fc in flashcards_data:
            Flashcard.objects.create(
                furniture=furniture,
                user=user,
                front=fc["front"],
                back=fc["back"],
                interval=fc.get("interval", 1),
                ease_factor=fc.get("ease_factor", 2.5),
                repetition=fc.get("repetition", 0),
                next_review=fc.get("next_review", timezone.now())
            )

        return JsonResponse({
            "id": furniture.id,
            "roomId": furniture.room.id,
            "name": furniture.name,
            "description": furniture.description,
            "flashcards": [
                {
                    "id": fc.id,
                    "front": fc.front,
                    "back": fc.back,
                    "interval": fc.interval,
                    "ease_factor": fc.ease_factor,
                    "repetition": fc.repetition,
                    "next_review": fc.next_review.isoformat()
                }
                for fc in furniture.flashcards.all()
            ],
        }, status=201)

@csrf_exempt
def furniture_detail(request, furniture_id):
    """
    GET = fetch one furniture
    PUT = update
    DELETE = delete
    """
    try:
        furniture = Furniture.objects.get(id=furniture_id)
    except Furniture.DoesNotExist:
        return JsonResponse({"error": "Furniture not found"}, status=404)

    if request.method == "GET":
        return JsonResponse({
            "id": furniture.id,
            "roomId": furniture.room.id,
            "name": furniture.name,
            "description": furniture.description,
            "flashcards": [
                {
                    "id": fc.id,
                    "front": fc.front,
                    "back": fc.back,
                    "interval": fc.interval,
                    "ease_factor": fc.ease_factor,
                    "repetition": fc.repetition,
                    "next_review": fc.next_review.isoformat()
                }
                for fc in furniture.flashcards.all()
            ],
        })

    if request.method == "PUT":
        body = json.loads(request.body)
        furniture.name = body.get("name", furniture.name)
        furniture.description = body.get("description", furniture.description)

        if "roomId" in body:
            try:
                room = Room.objects.get(id=body["roomId"])
                furniture.room = room
            except Room.DoesNotExist:
                return JsonResponse({"error": "Room not found"}, status=404)

        furniture.save()

        if "flashcards" in body:
            for fc_data in body["flashcards"]:
                if "id" in fc_data:
                    try:
                        fc = Flashcard.objects.get(id=fc_data["id"], furniture=furniture)
                        fc.front = fc_data.get("front", fc.front)
                        fc.back = fc_data.get("back", fc.back)
                        fc.interval = fc_data.get("interval", fc.interval)
                        fc.ease_factor = fc_data.get("ease_factor", fc.ease_factor)
                        fc.repetition = fc_data.get("repetition", fc.repetition)
                        if "next_review" in fc_data:
                            fc.next_review = fc_data["next_review"]
                        fc.save()
                    except Flashcard.DoesNotExist:
                        continue
                else:
                    Flashcard.objects.create(
                        furniture=furniture,
                        user=furniture.user,
                        front=fc_data["front"],
                        back=fc_data["back"],
                        interval=fc_data.get("interval", 1),
                        ease_factor=fc_data.get("ease_factor", 2.5),
                        repetition=fc_data.get("repetition", 0),
                        next_review=fc_data.get("next_review", timezone.now())
                    )

        return JsonResponse({
            "id": furniture.id,
            "roomId": furniture.room.id,
            "name": furniture.name,
            "description": furniture.description,
            "flashcards": [
                {
                    "id": fc.id,
                    "front": fc.front,
                    "back": fc.back,
                    "interval": fc.interval,
                    "ease_factor": fc.ease_factor,
                    "repetition": fc.repetition,
                    "next_review": fc.next_review.isoformat()
                }
                for fc in furniture.flashcards.all()
            ],
        })

    if request.method == "DELETE":
        furniture.delete()
        return JsonResponse({"status": "deleted"})


@csrf_exempt
def review_flashcard(request):
    """
    POST -> apply SM-2 algorithm to one flashcard
    body = { "furnitureId": int, "cardId": int, "grade": 0-5 }
    """
    if request.method != "POST":
        return JsonResponse({"error": "Only POST allowed"}, status=405)

    body = json.loads(request.body)

    furniture_id = body.get("furnitureId")
    card_id = body.get("cardId")
    grade = body.get("grade")

    # Validate
    if grade is None or not (0 <= grade <= 5):
        return JsonResponse({"error": "grade must be 0–5"}, status=400)

    try:
        furniture = Furniture.objects.get(id=furniture_id)
    except Furniture.DoesNotExist:
        return JsonResponse({"error": "Furniture not found"}, status=404)

    # Find card
    card_list = furniture.flashcards
    card = next((c for c in card_list if c["id"] == card_id), None)

    if not card:
        return JsonResponse({"error": "Flashcard not found"}, status=404)

    # Apply SM-2 update
    updated = apply_sm2(card, grade)

    # Replace card in the list
    for i, c in enumerate(card_list):
        if c["id"] == card_id:
            card_list[i] = updated
            break

    furniture.flashcards = card_list
    furniture.save()

    return JsonResponse(updated, safe=False)

@csrf_exempt
def review_queue(request):
    """
    GET -> return flashcards that should be reviewed now
    Optional param: ?furnitureId=1
    """
    if request.method != "GET":
        return JsonResponse({"error": "Only GET allowed"}, status=405)

    furniture_id = request.GET.get("furnitureId")

    if furniture_id:
        furnitures = Furniture.objects.filter(id=furniture_id)
    else:
        furnitures = Furniture.objects.all()

    now = timezone.now()

    cards_due = []

    for f in furnitures:
        for card in f.flashcards:
            next_review = card.get("next_review")
            if next_review and timezone.datetime.fromisoformat(next_review.replace("Z", "+00:00")) <= now:
                cards_due.append({
                    "furnitureId": f.id,
                    "cardId": card["id"],
                    "front": card["front"],
                    "back": card["back"],
                    "next_review": next_review,
                })

    return JsonResponse(cards_due, safe=False)


@csrf_exempt
def flashcard_list(request):
    """
    GET /api/questions     -> list all flashcards
    POST /api/questions    -> create new flashcard
    """
    if request.method == "GET":
        cards = Flashcard.objects.all()
        data = [
            {
                "id": c.id,
                "front": c.front,
                "back": c.back,
                "interval": c.interval,
                "ease_factor": c.ease_factor,
                "repetition": c.repetition,
                "next_review": c.next_review.isoformat(),
            }
            for c in cards
        ]
        return JsonResponse(data, safe=False)

    if request.method == "POST":
        body = json.loads(request.body)

        card = Flashcard.objects.create(
            front=body["front"],
            back=body["back"],
            interval=body.get("interval", 1),
            ease_factor=body.get("ease_factor", 2.5),
            repetition=body.get("repetition", 0),
            next_review=body.get("next_review"),
        )

        return JsonResponse({"id": card.id}, status=201)


@csrf_exempt
def flashcard_detail(request, card_id):
    """
    GET /api/questions/id       -> get specific question
    PUT /api/questions/id       -> update
    DELETE /api/questions/id    -> delete
    """
    try:
        card = Flashcard.objects.get(id=card_id)
    except Flashcard.DoesNotExist:
        return JsonResponse({"error": "Flashcard not found"}, status=404)

    if request.method == "GET":
        return JsonResponse({
            "id": card.id,
            "front": card.front,
            "back": card.back,
            "interval": card.interval,
            "ease_factor": card.ease_factor,
            "repetition": card.repetition,
            "next_review": card.next_review.isoformat(),
        })

    if request.method == "PUT":
        body = json.loads(request.body)

        card.front = body.get("front", card.front)
        card.back = body.get("back", card.back)
        card.interval = body.get("interval", card.interval)
        card.ease_factor = body.get("ease_factor", card.ease_factor)
        card.repetition = body.get("repetition", card.repetition)
        card.next_review = body.get("next_review", card.next_review)

        card.save()

        return JsonResponse({"status": "updated"})

    if request.method == "DELETE":
        card.delete()
        return JsonResponse({"status": "deleted"})