name: "Setup Node.js"
description: "Install Node.js and cache"
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "22.21.1"
        cache: "npm"
        cache-dependency-path: "./client/package-lock.json"
