# Generated by Django 5.2.8 on 2025-11-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='questions',
        ),
        migrations.AddField(
            model_name='furniture',
            name='flashcards',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
