# Generated by Django 5.2.8 on 2025-12-03 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_flashcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='flashcards',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='furniture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='api.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='furniture', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
