# Generated by Django 5.2.8 on 2025-12-03 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_furniture_flashcards_flashcard_furniture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='api.furniture'),
        ),
    ]
