# Generated by Django 5.2.8 on 2026-01-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_palacetemplate_remove_furniture_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
